# Generated by Django 4.1 on 2022-08-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ant_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AntDoc',
            new_name='AntDoc',
        ),
    ]
